### ISSUE TITLE
Word's slug related links | MultipleObjectsReturned exception

### ISSUE THREAD

**Issue by harmo** [harmo/dicodigital-api#11]
Actually the word's links defined by the _url_ field in serializer is load with the autoslug field based on word's label.

![](http://i.imgur.com/hWppHpR.png)

In the case of `+1` and `1` words, the slugs are exactly the same and produce a MultipleObjectsReturned exception during a GET or PUT request.

This related link must be construct with the word pk, and the slug must be used for search only, with its dedicated url to prevent conflict between a numeric word type and a PK.

**Comment by Anaethelion** [comment]
I suggest we use UUID instead of a slug thus leaving the url lookup empty of collision.
We can still have a filter if we need to search the pool.

What do you think ?

**Comment by harmo** [comment]
Oops already fix that :D 

I just add a filter to have the **?search=** GET parameter in word-list view, who returns an OrderedDict of results.

The word-detail is now based on PK, there is no conflicts at all. 

If you want to change the lookup_field to the **UUID** I'm ok ;)
I 'll merge my fix in few minutes, I suggest you to open a new PR if you want the UUID feature.

**Comment by harmo** [comment]
This issue is outdated since PR #14
