### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by harmo** [harmo/dicodigital-api#16]
https://trello.com/c/l4ojtvzA/9-pouvoir-voter-1-1

**Comment by harmo** [comment]
@enguerran 
Je suis en train de plancher sur le système de votes et étant donné qu'ils seront tous anonymes, je compte enregistrer dans l'API l'adresse IP et un cookie pour déterminer si l'utilisateur a déjà voté.

Je me pose une question car je ne suis pas sûr d'un truc:
L'adresse que je vais récupérer via la variable REMOTE_ADDR sera celle du serveur où se trouvera le front, et pas celle de l'utilisateur qui clique exact ? Si c'est le cas je ne vois pas comment faire…

**Comment by enguerran** [comment]
@harmo 
C'est une variable Django ça, `REMOTE_ADDR` ?
J'imagine que cette réponse conviendra pour récupérer l'adresse IP du end user : https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django
